sudo: required

language: rust

rust:
    - nightly

cache: cargo

before_install:
    - openssl aes-256-cbc -K $encrypted_3d130dceec06_key -iv $encrypted_3d130dceec06_iv -in compute-engine-creds.json.enc -out compute-engine-creds.json -d
    - curl https://sdk.cloud.google.com | bash
    - tar -xf credentials.tar.gz
    - mkdir -p lib
    - gcloud auth activate-service-account --key-file client-secret.json

services:
    - docker

script:
    - cargo build --verbose
    - cargo test --verbose
    - docker build -t todo-tree .
    - docker ps -a
    - docker save -o todo-tree.tar todo-tree
    - gcloud compute --project "todo-tree-216306" scp todo-tree.tar todo-tree-backend-1:~ --zone "us-west1-b"
